# -*- coding: utf-8 -*-
{
    'name': 'VZ - Subscription Planning',
    'version': '11.0.1.0.0',
    'category': 'Generic Module',
    'summary': 'Subscription customization',
    'author': 'ERP|OPEN',
    'depends': [
        'sale',
        'sale_subscription',
        'dev_sale_delivery_by_dates',
        'sale_order_type',
        'sale_order_dates',
        'delivery',
        'web',
        'web_grid',
        'vz_sale',
        'stock',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        #'views/templates.xml',
        'views/sale_subscription.xml',
        'views/sale_subscription_planning.xml',
        'views/sale_subscription_planning_line.xml',
        'views/sale_subscription_planning_change.xml',
        'views/stock_picking.xml',
        'views/sale_order.xml',
        'wizard/massive_change_wizard.xml',
        'wizard/multi_massive_change_wizard.xml',
        'wizard/temporary_subscription_block_wizard.xml',
        'menuitems.xml',
    ],
    'installable': True,
}